### ISSUE TITLE
Any glitches with dualboot?

### ISSUE THREAD

**Issue by chrismaster** [craigcabrey/thinkbook-13x-gen4-enablement#4]
Wann bring fedora on my new thinkbook.
Thanks for your work... Looks like fedora is usable on the 13x
Is there something to watch out for a fresh dual boot system? ...or just resize in Win and install fedora on the new spare space?

**Comment by craigcabrey** [comment]
You'll need to disable bit locker encryption in order to resize the partition. 

You'll also want to disable secure boot validation on the Fedora side (mokutil --disable-validation).

Windows Hello will be disabled after this operation, at least until you re-enroll your fingerprints etc.

**Comment by chrismaster** [comment]
It might be better, to resize in windows with the Win disk managment, so no change to BitLocker. I'll give it a try...
Thx for the help and this github repo

**Comment by chrismaster** [comment]
for dual boot all I had to do is:
- resize partition with disk manager in windows
- disable secure boot in bios (F1 security->secure boot ...)
- standard installation of fedora 40 with a usb mouse

your COPR repository is great, sound works out of the box.
I had to install the trackpad module by hand... Is the kernel module for the trackpad (goodix-gt7868q.ko) in your COPR kernel? Maybe I did something wrong... :-)

**Comment by craigcabrey** [comment]
The goodix driver isn't in that kernel package. I couldn't figure out a way to patch it into the kernel nicely, so I'm going to package it as a dkms module for now.

**Comment by craigcabrey** [comment]
I've added `goodix-gt7868q-dkms` to the COPR repo, let me know if you have any issues with using it.

**Comment by bonjour81** [comment]
Hi!
I am quite interested in this laptop thanks to this great work here!! 
As far as I understood, except webcam and a couple of minor items (Mic mute hot key led & Fn+Q), it all working? (I see little activity last monthes here). Not a big deal in my use. 

I wanted to ask :  is this `mokutil --disable-validation`  fedora specific or applicable to all distros (I use Manjaro on my just dead XPS so I would prefer use it on next one too)

**Comment by craigcabrey** [comment]
Yes, it's all working. Actually Fn+Q does work, it just doesn't propagate all the way back to the UI for some reason. 

Camera works in Fedora 42 now, though quality isn't great. 

Mokutil shouldn't be Fedora specific, but it depends on your bootloader setup. Manjaro might require extra work, I'm not up to date on the Arch world anymore.
