### ISSUE TITLE
Mouse / touchpad input devices have periodic low polling frequency

### ISSUE THREAD

**Issue by madenvel** [craigcabrey/thinkbook-13x-gen4-enablement#5]
Fedora 40 + kernel 6.10rc5 

Most often than not the pointing device polling frequency seems quite low (both bluetooth, USB wired and the  touchpad with goodix custom kernel module).

Not sure what the root-cause yet, I've seen it on other systems before but not as bad as here. Will update if find the culprit.

**Comment by craigcabrey** [comment]
almost certainly it's intel's psr. try disabling it

**Comment by madenvel** [comment]
Thanks, looks like it. If that's actually the panel that reduces the update frequency then disabling this will impact the battery life, I suppose. Anyway, with such lag it is quite hard to use the laptop.

**Comment by craigcabrey** [comment]
Yea, my anecdote is that it saves 1-2 watts. I plan on tying it to the power save profile via the debugfs flag.

Not sure why it's buried there since it's runtime configurable on windows. 🤷‍♂️
