### ISSUE TITLE
Left and right audio channel are swapped

### ISSUE THREAD

**Issue by madenvel** [craigcabrey/thinkbook-13x-gen4-enablement#6]
Kernel 6.10rc5 - left is actually right and vice versa

**Comment by craigcabrey** [comment]
Same here, hah. I'll try and get to opening a bug upstream sometime this week

**Comment by madenvel** [comment]
Sent a patch to the kernel mailing list.
Can be found in [github](https://github.com/torvalds/linux/pull/900) as well.

**Comment by madenvel** [comment]
The patch has been applied to the kernel.
